### 列表和数组

#### 一维列表

In [ ]:
list_a=[1,2,3,4,5]

In [ ]:
list_a

In [ ]:
type(list_a)

#### 二维列表 数组

In [ ]:
list_b=[[1,2],[3,4],[5,6]]

In [ ]:
list_b

输出数字2

In [ ]:
list_b[0][1]
#因为2是数组中第一行的第二列 一行二列从零开始数的话变为[0][1]

### Numpy 高效处理数组

#### 创建列表

In [ ]:
#导入Numpy
import numpy as np
#创建列表
list_c=[1,2,3,4]
type(list_c)#list类型
print(list_c)

#### 把列表转为Numpy数组

In [ ]:
my_array=np.array(list_c)#[1 2 3 4]
type(my_array)#numpy.ndarray类型
print(my_array)

#### 创建连续数字的数组 np.arange()

In [ ]:
#创建0-9的数字
np.arange(10)#输出[0 1 2 3 4 5 6 7 8 9]
#创建有间隔步长的数字
np.arange(0,10,2)#输出[0 2 4 6 8] 0到10间隔为2

#### 创建带值的数组 0或1

In [ ]:
np.ones(5)#创建一个包含5个1的数组 输出[1. 1. 1. 1. 1.]
np.zeros(5)#创建一个包含5个0的数组 输出[0. 0. 0. 0. 0.]

#### 创建值指定行列的数组 shape=(行数, 列数) 形状表格

In [ ]:
np.ones(shape=(3,4))#创建一个3行4列的数组 

#### 创建随机数 np.random.randint()




In [ ]:
#创建0-100的随机10个整数
arr=np.random.randint(0,100,10)

#### 获取最大值/最小值/平均值&最大值的索引值

In [ ]:
print(arr.max())#最大值
print(arr.min())#最小值
print(arr.mean())#平均值
print()#换行
#取索引///////////////
print(arr.argmax())#最大值的索引值
print(arr.argmin())#最小值的索引值

#### 查看大小 xxx.shape

In [ ]:
arr.shape

#### 转换数组形状 reshape((行,列))

In [ ]:
print(arr)#原来的形状
arr.reshape((5,2))#将数组变为5行2列的形式
#超出原有的数量会报错

#### Numpy&矩阵

In [ ]:
#创建10*10的矩阵
matrix = np.arange(0,100).reshape((10,10))#将数组变为10行10列的形式

In [ ]:
matrix

In [ ]:
#取值 3行5列
matrix[2][4]

In [ ]:
#取某一行的值  取2行的值
matrix[1,:]

In [ ]:
#取某一列的值 取2列的值
print(matrix[:,1])#[ 1 11 21 31 41 51 61 71 81 91]
#把去除的列值改为竖着的
matrix[:,1].reshape((10,1))#10行1列的矩阵 行变列

In [ ]:
#矩阵切片 区域取值 
# 取2到3行和第2到4列的区域元素
matrix[0:3,1:4]

In [73]:
#矩阵区域切片赋值
matrix[0:3,1:4]=0#将矩阵的第0行到第2行，第1列到第3列的区域赋值为0
print(matrix)

[[ 0  0  0  0  4  5  6  7  8  9]
 [10  0  0  0 14 15 16 17 18 19]
 [20  0  0  0 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
